#pragma once

#include <LibraryIndexFile.h>

#include <cstdint>

#include "activities/Activity.h"

struct Rect;

// Walks the whole card once, rebuilds the library index with the titles and
// authors read from inside the books, then prepares the cover of every book it
// found.
//
// Covers are the slow half: the first time a book's cover is wanted the reader
// has to inflate and dither it, which is why it normally happens while someone
// waits on the home screen. Doing all of them here, up front, is the whole
// point of the app — afterwards every screen that shows a cover reads a ready
// bitmap off the card.
//
// One book per loop pass, so Back stays responsive on a card with hundreds of
// books. Work already done is skipped: a second run over an unchanged card
// only re-reads the index.
class LibraryScanActivity final : public Activity {
 public:
  LibraryScanActivity(GfxRenderer& renderer, MappedInputManager& mappedInput)
      : Activity("LibraryScan", renderer, mappedInput) {}

  void onEnter() override;
  void onExit() override;
  void loop() override;
  void render(RenderLock&&) override;
  // The scan owns the card for minutes at a time; sleeping mid-walk would
  // leave a half-written cover cache behind.
  bool preventAutoSleep() override { return phase == Phase::Indexing || phase == Phase::Covers; }
  // One book per loop pass only pays off at full clock and without the idle
  // delay: otherwise the loop spends 10 to 50 ms waiting between books and
  // drops the CPU frequency in the middle of decoding a cover.
  bool skipLoopDelay() override { return phase == Phase::Indexing || phase == Phase::Covers; }

 private:
  enum class Phase : uint8_t {
    Ready,     // waiting for the user to start
    Indexing,  // one blocking walk of the card
    Covers,    // one book per pass
    Done,
  };

  void startScan();
  void runIndexPass();
  void processNextBook();
  void drawReady(const Rect& content);
  void drawProgress(const Rect& content);
  void drawSummary(const Rect& content);

  library::LibraryIndexFile index;
  Phase phase = Phase::Ready;
  bool indexFailed = false;
  bool cancelled = false;
  // Books carried by the index this run, and how far down it we are.
  uint16_t bookCount = 0;
  uint16_t processed = 0;
  uint16_t coversReady = 0;    // already cached when we got there
  uint16_t coversCreated = 0;  // generated by this run
  uint16_t coversMissing = 0;  // book has no cover we can render
  int thumbHeight = 0;
  uint32_t startedMs = 0;
  uint32_t elapsedMs = 0;
};
